name: githubWorkflow

on: push

jobs:
    job1:
        name: First Job
        uses: actions/checkout@v2
        runs-on: ubuntu-latest
        steps:
       -name: step one
       -name: step two
        run: env | sort
    job2:
        name: Second Job
        uses: actions/checkout@v2
        runs-on: windows-latest
        steps:
       -name: step one
       -name: step two
        run: "Get=ChildItem Evn: | Sort-Object Name"
